name: learn-github-actions

on: [push]
jobs:
  learning-github-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello
        run: echo "The user has pushed code"
      - name: install and run scripts
        run: |
          pip install -r requirements.txt
          python main.py
